apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: messenger
resources:
  - k8s/infra
  - k8s/app.yaml
  - k8s/monitoring.yaml
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=monitoring/prometheus-kubernetes.yml
      - alerts.yml=monitoring/alerts.yml
  - name: grafana-datasource
    files:
      - prometheus.yml=monitoring/datasource.yml
  - name: grafana-provider
    files:
      - messenger.yml=monitoring/dashboards.yml
  - name: grafana-dashboard
    files:
      - messenger.json=monitoring/messenger.json
